"""add_rejected_to_remediation_plans

Revision ID: a12bf4f29bd6
Revises: 0583459cb2ff
Create Date: 2026-05-04 21:17:34.566559

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a12bf4f29bd6"
down_revision: Union[str, None] = "0583459cb2ff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "remediation_plans",
        sa.Column("rejected", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column("remediation_plans", "rejected", server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("remediation_plans", "rejected")
    # ### end Alembic commands ###
